### ISSUE TITLE
regression following last emu8950 update (notesel)

### ISSUE THREAD

**Issue by yoyofr** [digital-sound-antiques/libkss#10]
Hi,

I noticed a bug following the latest emu8950 update (with the notesel change).

For some kss files, there's no output anymore. You can try with 
http://ftp.modland.com/pub/modules/KSS/Crystal%20Score/callisto%27s%20theme.kss

**Comment by okaxaki** [comment]
Hi,

This bug was introduced when status reset feature was supported at [this commit of emu8950](https://github.com/digital-sound-antiques/emu8950/commit/987f59731e42dd43e881a41fc2a5b957f4cfaa7f). I have fixed both [libkss](https://github.com/digital-sound-antiques/libkss/commit/636865861cebc704de892636fa039925e0c5cdd7) and [emu8950](https://github.com/digital-sound-antiques/emu8950/commit/3da25663047a31a9df63c06638db40e8ede65ead). 

Thank you for reporting!

**Comment by yoyofr** [comment]
thanks for the fast fix! I'm integrating libkss in modizer, it's working perfectly now.
