### ISSUE TITLE
Volume from separate channels

### ISSUE THREAD

**Issue by niekvlessert** [digital-sound-antiques/libkss#2]
It would be amazing if I can create an equalizer for every separate channel in the music. The player obviously delivers 2 audio channels, so that's not the way to go, I don't think I can currently have this data? Can you please shed some light on this?

**Comment by okaxaki** [comment]
yeah, it sounds amazing... but unfortunately libkss dose not provide API for separate output for each devices or channel in a device. Currently, to obtain each channels output data, we need to modify inside calc function (ex. `KSSPLAY_calc` for devices. `PSG_calc`, `SCC_calc` and `OPLL_calc` for channels). 

Anyway this idea is worthy of consideration as regular API in future so I labelled this issue enhancement.

**Comment by niekvlessert** [comment]
Great. :)

**Comment by arouge** [comment]
Hi Niekniek.
In order to adjust volume per channel, you can rely on the provided interface made by Okaxaki:

void KSSPLAY_set_device_volume(KSSPLAY *kssplay, uint32_t devnum, int32_t vol);

ie.

```
KSSPLAY_set_device_volume(kssplay, EDSC_PSG, 0);
KSSPLAY_set_device_volume(kssplay, EDSC_SCC, -20);
KSSPLAY_set_device_volume(kssplay, EDSC_OPL, -4);
KSSPLAY_set_device_volume(kssplay, EDSC_OPLL, -40);
```
Additionnaly, please note that volume above 0 may lead to crack. Therefore, I balance channels with value below 0.

Hope this helps.

**Comment by okaxaki** [comment]
I close this issue because #6 provides separate channel output and the volume can be controlled outside of the library.
